apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dock-tools

resources:
  - namespace.yaml
  - configmap-nginx.yaml
  - configmap-manager.yaml
  - deployment-manager.yaml
  - deployment-nginx.yaml
  - service-manager.yaml
  - service-nginx.yaml
